version: '3.10'

services:

  db:
      container_name: postgres_airbnb_db
      build:
        dockerfile: Dockerfile_postgres
      image: postgres:alpine
      restart: always
      env_file:
        - .env
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data/

  api:
    container_name: api_airbnb
    build: 
      context: .
      dockerfile: Dockerfile_api
    volumes:
      - .:/api
    environment:
      - POSTGRES_LINK=$POSTGRES_LINK
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure

volumes:
  pg_data: