FROM postgres:alpine
COPY raw_data/merged.csv merged.csv
COPY *.sql /docker-entrypoint-initdb.d/
ADD setup_tables.sql /docker-entrypoint-initdb.d
RUN chmod a+r /docker-entrypoint-initdb.d/*.sql

ENV POSTGRES_HOST_PORT=$POSTGRES_HOST_PORT

EXPOSE 6666
