version: '3.10'

#combines the different images you want to create
services:

  db:
      container_name: airbnb_postgres_c
      build:
        # seperate docker file for postgres
        dockerfile: Dockerfile_postgres
      image: airbnb_postgres
      restart: always
      env_file:
        - .env
      ports:
      #maps outside_port:container_port
        - "5432:5432"
      #volume on where to persist the data for future use
      volumes:
        - pg_data:/var/lib/postgresql/data/

  api:
    container_name: airbnb_api_c
    build: 
      context: .
      dockerfile: Dockerfile_api
    image: airbnb_api
    volumes:
      - .:/api
    env_file:
        - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure

volumes:
  pg_data: