FROM postgres:alpine
COPY *.sql /docker-entrypoint-initdb.d/
ADD setup.sql /docker-entrypoint-initdb.d
RUN chmod a+r /docker-entrypoint-initdb.d/*

ENV POSTGRES_HOST_PORT=$POSTGRES_HOST_PORT

EXPOSE 6666
